shallow_clone: true

platform:
  - x86
  # - x64

configuration:
  - Debug
  # - Release

image:
  - Visual Studio 2015
  # - Visual Studio 2017

cache:
  - C:\cmake-3.8.0-win32-x86
  - C:\Program Files (x86)\IntelSWTools
  - C:\w_mkl_2018.0.124.exe

environment:
  matrix:
    # - BLAS_VERSION: Intel10_32
    # - BLAS_VERSION: Intel10_64lp
    - BLAS_VERSION: Intel10_64lp_seq
    # - BLAS_VERSION: Intel


init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: MD c:\logs\
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;$env:PATH"
  - ps: |
      if (![IO.File]::Exists("C:\w_mkl_2018.0.124.exe")) {
        ECHO 'w_mkl_2018.0.124.exe does not exist. Preparing to install MKL ..'
        Start-FileDownload 'http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12079/w_mkl_2018.0.124.exe' -FileName 'C:\w_mkl_2018.0.124.exe'
        C:\w_mkl_2018.0.124.exe -s -l c:\logs\extract-mkl.log -a install --eula=accept --components=all --output='C:\logs\install-mkl-output.txt' --installdir='C:\Program Files (x86)\IntelSWTools' --log='c:\logs\install-mkl.log' | Out-Null
        ECHO 'Done'
        TYPE C:\logs\install-mkl-output.txt 
      }
      else{
        ECHO 'w_mkl_2018.0.124.exe already existed'
      }
      $env:LD_MKL_PATH='C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.0.124\windows\mkl\lib\intel64_win\'
      ECHO "mkl path is $env:LD_MKL_PATH"
      ls $env:LD_MKL_PATH
      $env:PATH="$env:LD_MKL_PATH;$env:PATH"


before_build:
  - "ECHO %BLAS_VERSION%"
  - "ECHO 'cmake .. -DBLA_VENDOR=%BLAS_VERSION% -DBLAS_DIR=C:\\cmake-3.8.0-win32-x86\\share\\cmake-3.8\\Modules'"
  - ps: |
      mkdir build
      cd build
  - "cmake .. -DBLA_VENDOR=%BLAS_VERSION% -DBLAS_DIR=$env:LD_MKL_PATH -DCMAKE_CURRENT_LIST_DIR_xxx=C:\\cmake-3.8.0-win32-x86\\share\\cmake-3.8\\Modules"

build_script:
  - cmake --build .

test_script:

deploy: off

on_failure:
  - appveyor PushArtifact CMakeCache.txt
  - appveyor PushArtifact CMakeFiles/CMakeOutput.log
  - appveyor PushArtifact CMakeFiles/CMakeError.log


on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
